# Generated by Django 5.1.2 on 2024-10-20 21:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('poster_path', models.CharField(blank=True, max_length=200, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(null=True, unique=True)),
                ('company', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.BooleanField(blank=True, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=200, null=True)),
                ('belongs_to_collection', models.BooleanField(default=False)),
                ('budget', models.IntegerField()),
                ('homepage', models.CharField(blank=True, max_length=200, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('original_title', models.CharField(max_length=200)),
                ('overview', models.CharField(blank=True, max_length=2000, null=True)),
                ('popularity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('poster_path', models.CharField(blank=True, max_length=200, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('revenue', models.BigIntegerField()),
                ('runtime', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('tagline', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(max_length=200)),
                ('tmdb_id', models.IntegerField(null=True, unique=True)),
                ('vote_average', models.DecimalField(decimal_places=1, max_digits=5)),
                ('vote_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(null=True, unique=True)),
                ('genre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(null=True, unique=True)),
                ('keyword', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, null=True, unique=True)),
                ('language', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.BooleanField()),
                ('gender', models.IntegerField()),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('known_for_department', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('popularity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('profile_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LT_Films_Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filmproject.company')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filmproject.film')),
            ],
        ),
        migrations.CreateModel(
            name='LT_Films_Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filmproject.country')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filmproject.film')),
            ],
        ),
        migrations.CreateModel(
            name='LT_Films_Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filmproject.film')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filmproject.language')),
            ],
        ),
        migrations.CreateModel(
            name='LT_Films_Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_id', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filmproject.film')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filmproject.person')),
            ],
        ),
        migrations.CreateModel(
            name='LT_Films_Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_id', models.IntegerField()),
                ('character', models.CharField(max_length=200)),
                ('credit_id', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filmproject.film')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filmproject.person')),
            ],
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True, verbose_name='Email')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LT_Films_Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filmproject.film')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filmproject.genre')),
            ],
            options={
                'unique_together': {('film', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filmproject.film')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filmproject.keyword')),
            ],
            options={
                'unique_together': {('film', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='LT_Viewer_Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchlist', models.BooleanField(default=False)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filmproject.film')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filmproject.viewer')),
            ],
            options={
                'indexes': [models.Index(fields=['viewer', 'film'], name='filmproject_viewer__159eba_idx')],
            },
        ),
        migrations.CreateModel(
            name='LT_Viewer_Seen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_film', models.BooleanField(default=False)),
                ('viewer_rating', models.DecimalField(decimal_places=8, max_digits=9, null=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filmproject.film')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filmproject.viewer')),
            ],
            options={
                'indexes': [models.Index(fields=['viewer', 'film'], name='filmproject_viewer__2f3ddb_idx')],
            },
        ),
        migrations.CreateModel(
            name='LT_Viewer_Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('a_points', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('film_a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='film_a', to='filmproject.film')),
                ('film_b', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='film_b', to='filmproject.film')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filmproject.viewer')),
            ],
            options={
                'unique_together': {('viewer', 'film_a', 'film_b')},
            },
        ),
    ]
