# Generated by Django 5.1.2 on 2024-12-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lt_viewer_cosine_similarity',
            name='cosine_similarity',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
