# Generated by Django 5.1.2 on 2024-12-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0002_alter_lt_viewer_cosine_similarity_cosine_similarity_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lt_viewer_cosine_similarity',
            name='filmproject_viewer__b16745_idx',
        ),
        migrations.AlterField(
            model_name='lt_viewer_ratings',
            name='a_points',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='lt_viewer_ratings',
            name='b_points',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
