# Generated by Django 5.0.7 on 2024-08-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0002_genre_tmdb_id_lt_viewer_ratings_user_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='tmdb_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
