# Generated by Django 5.1.2 on 2024-12-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0003_remove_lt_viewer_cosine_similarity_filmproject_viewer__b16745_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lt_viewer_watchlist',
            name='filmproject_viewer__159eba_idx',
        ),
        migrations.AlterUniqueTogether(
            name='lt_viewer_watchlist',
            unique_together={('viewer', 'film')},
        ),
    ]
