# Generated by Django 5.1.2 on 2024-10-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0003_remove_lt_viewer_seen_viewer_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='lt_viewer_seen',
            name='viewer_rating',
            field=models.DecimalField(decimal_places=8, max_digits=9, null=True),
        ),
    ]
