# Generated by Django 5.1.2 on 2024-10-22 18:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0004_lt_viewer_seen_viewer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lt_viewer_ratings',
            name='a_points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='lt_viewer_ratings',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='lt_viewer_ratings',
            name='film_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='film_a', to='filmproject.film'),
        ),
        migrations.AlterField(
            model_name='lt_viewer_ratings',
            name='film_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='film_b', to='filmproject.film'),
        ),
        migrations.AlterField(
            model_name='lt_viewer_ratings',
            name='viewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='filmproject.viewer'),
        ),
    ]
