# Generated by Django 5.1.2 on 2024-12-01 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0004_remove_lt_viewer_watchlist_filmproject_viewer__159eba_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='viewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
