# Generated by Django 5.0.7 on 2024-08-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0005_alter_lt_films_genres_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='adult',
            field=models.BooleanField(null=True),
        ),
    ]
