# Generated by Django 5.0.7 on 2024-08-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0006_alter_film_adult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='adult',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
