# Generated by Django 5.1.2 on 2024-10-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0006_alter_viewer_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_pfp.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
