# Generated by Django 5.0.7 on 2024-08-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0007_alter_film_adult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='tmdb_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='lt_films_keywords',
            unique_together={('film_id', 'keyword_id')},
        ),
    ]
