# Generated by Django 5.1.2 on 2024-10-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0008_alter_film_revenue_alter_film_runtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='budget',
            field=models.IntegerField(null=True),
        ),
    ]
