# Generated by Django 5.0.7 on 2024-08-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0008_alter_keyword_tmdb_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lt_films_keywords',
            old_name='film_id',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='lt_films_keywords',
            old_name='keyword_id',
            new_name='keyword',
        ),
    ]
