# Generated by Django 5.0.7 on 2024-08-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0009_rename_film_id_lt_films_keywords_film_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lt_films_genres',
            old_name='film_id',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='lt_films_genres',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.AlterUniqueTogether(
            name='lt_films_genres',
            unique_together={('film', 'genre')},
        ),
    ]
