# Generated by Django 5.1.2 on 2024-10-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0009_alter_film_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='vote_count',
            field=models.IntegerField(null=True),
        ),
    ]
