# Generated by Django 5.0.7 on 2024-08-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0010_rename_film_id_lt_films_genres_film_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lt_films_cast',
            old_name='film_id',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='lt_films_cast',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='lt_films_companies',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='lt_films_companies',
            old_name='film_id',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='lt_films_countries',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='lt_films_countries',
            old_name='film_id',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='lt_films_crew',
            old_name='film_id',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='lt_films_crew',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='lt_films_languages',
            old_name='film_id',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='lt_films_languages',
            old_name='language_id',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='lt_seen_films',
            old_name='film_id',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='lt_seen_films',
            old_name='viewer_id',
            new_name='viewer',
        ),
        migrations.RenameField(
            model_name='lt_viewer_ratings',
            old_name='film_id',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='lt_viewer_ratings',
            old_name='viewer_id',
            new_name='viewer',
        ),
    ]
