# Generated by Django 5.1.2 on 2024-10-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0010_alter_film_vote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='vote_average',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
