# Generated by Django 5.0.7 on 2024-08-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0011_rename_film_id_lt_films_cast_film_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tmdb_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
