# Generated by Django 5.0.7 on 2024-08-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0012_company_tmdb_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='company',
        ),
    ]
