# Generated by Django 5.0.7 on 2024-08-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0013_rename_company_name_company_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=10),
        ),
    ]
