# Generated by Django 5.1.2 on 2024-10-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0013_alter_film_vote_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='adult',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='known_for_department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='popularity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
