# Generated by Django 5.1.2 on 2024-10-25 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0015_alter_lt_films_cast_character_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lt_films_crew',
            name='credit_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lt_films_crew',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lt_films_crew',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='filmproject.film'),
        ),
        migrations.AlterField(
            model_name='lt_films_crew',
            name='job',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lt_films_crew',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='filmproject.person'),
        ),
    ]
