# Generated by Django 5.0.7 on 2024-08-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0015_rename_country_code_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_code',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='tmdb_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='email',
            field=models.CharField(max_length=200, unique=True, verbose_name='Email'),
        ),
    ]
