# Generated by Django 5.0.7 on 2024-08-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0016_alter_genre_genre_alter_keyword_keyword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='language_code',
        ),
        migrations.RemoveField(
            model_name='language',
            name='language_name',
        ),
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='tmdb_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
