# Generated by Django 5.1.2 on 2024-11-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0017_feedentry_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='accepted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='rejected_at',
            field=models.DateTimeField(null=True),
        ),
    ]
