# Generated by Django 5.0.7 on 2024-08-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0017_remove_language_language_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
