# Generated by Django 5.1.2 on 2024-11-07 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0017_feedentry_comment_like'),
        ('filmproject', '0017_lt_viewer_ratings_b_points'),
    ]

    operations = [
    ]
