# Generated by Django 5.1.2 on 2024-11-07 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0018_friendrequest_accepted_at_friendrequest_rejected_at'),
        ('filmproject', '0019_merge_20241107_2216'),
    ]

    operations = [
    ]
