# Generated by Django 5.1.2 on 2024-11-08 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0020_merge_20241107_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='LT_Viewer_Cosine_Similarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cosine_similarity', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('viewer_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='viewer_1', to='filmproject.viewer')),
                ('viewer_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='viewer_2', to='filmproject.viewer')),
            ],
            options={
                'unique_together': {('viewer_1', 'viewer_2')},
            },
        ),
    ]
