# Generated by Django 5.1.2 on 2024-11-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0021_lt_viewer_cosine_similarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='mlm_rating',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
    ]
