# Generated by Django 5.1.2 on 2024-10-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0021_rename_lt_seen_films_lt_viewer_seen_viewer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lt_viewer_watchlist',
            name='watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
