# Generated by Django 5.1.2 on 2024-11-11 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0022_film_mlm_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment')], max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='lt_viewer_seen',
            name='filmproject_viewer__2f3ddb_idx',
        ),
        migrations.AlterField(
            model_name='lt_viewer_seen',
            name='viewer_rating',
            field=models.DecimalField(decimal_places=8, default=0.5, max_digits=9, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='lt_viewer_seen',
            unique_together={('viewer', 'film')},
        ),
        migrations.AddField(
            model_name='notification',
            name='feed_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmproject.feedentry'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
