# Generated by Django 5.1.2 on 2024-10-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0022_alter_lt_viewer_watchlist_watchlist'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lt_viewer_seen',
            index=models.Index(fields=['viewer', 'film'], name='filmproject_viewer__2f3ddb_idx'),
        ),
    ]
