# Generated by Django 5.1.2 on 2024-10-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0023_lt_viewer_seen_filmproject_viewer__2f3ddb_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lt_viewer_watchlist',
            index=models.Index(fields=['viewer', 'film'], name='filmproject_viewer__159eba_idx'),
        ),
    ]
