# Generated by Django 5.1.2 on 2024-11-11 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0023_notification_and_more'),
        ('filmproject', '0023_remove_lt_viewer_seen_filmproject_viewer__2f3ddb_idx_and_more'),
    ]

    operations = [
    ]
