# Generated by Django 5.1.2 on 2024-10-18 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0024_lt_viewer_watchlist_filmproject_viewer__159eba_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='friends',
            field=models.ManyToManyField(blank=True, to='filmproject.viewer'),
        ),
        migrations.AddField(
            model_name='viewer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='filmproject.viewer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='filmproject.viewer')),
            ],
        ),
    ]
