# Generated by Django 5.1.2 on 2024-11-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmproject', '0024_alter_viewer_user'),
        ('filmproject', '0024_merge_20241111_2304'),
    ]

    operations = [
    ]
