name: Mountain Lion Flake8

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: 
          - 3.12
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Find location and check output file
        run: |
          pwd
          ls -l

      - name: Run Flake8 and store output
        run: |
          # Run flake8, excluding 'venv' and 'migrations' directories, and save the output to a file.
          flake8 filmproject --exclude=venv,migrations --count > flake8_report.txt || true  # Use '|| true' to prevent failure
  
      - name: Upload Flake8 output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: flake8-report-${{ github.run_id }}
          path: flake8_report.txt  # Correct path to the output file
